### ISSUE TITLE
Encounter issue when batch_size is bigger than 1

### ISSUE THREAD

**Issue by ueoo** [Jermmy/style-transfer-contextual-loss#1]
When I set the batch_size to 2 or other bigger values, the following issue raised:

```
Traceback (most recent call last):
  File "train.py", line 205, in <module>
    main(config)
  File "train.py", line 98, in main
    loss.backward()
  File "/Users/Gerry/miniconda3/envs/torch04/lib/python3.6/site-packages/torch/tensor.py", line 93, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "/Users/Gerry/miniconda3/envs/torch04/lib/python3.6/site-packages/torch/autograd/__init__.py", line 90, in backward
    allow_unreachable=True)  # allow_unreachable flag
RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation
```
Could please tell me how to solve it?

**Comment by ueoo** [comment]
Fix this bug by changing the following lines in `generator.py`
```
patches = features.reshape(shape=(1, 1, P, C)).permute((2, 3, 0, 1))
```
to
```
patches = features.view(1, 1, P, C).permute((2, 3, 0, 1))
```
AND
```
featureT_i = featureT[i, :, :, :].unsqueeze_(0)
featureI_i = featureI[i, :, :, :].unsqueeze_(0).permute((0, 3, 1, 2))
```
to
```
featureT_i = featureT[i, :, :, :].unsqueeze(0)
featureI_i = featureI[i, :, :, :].unsqueeze(0).permute((0, 3, 1, 2))
```

**Comment by Jermmy** [comment]
Thanks for your contribution!
